apiVersion: v1
kind: Service
metadata:
  name: efatura-frontend
  namespace: efatura
  labels:
    app: efatura-frontend
spec:
  type: ClusterIP
  selector:
    app: efatura-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
